# Generated by Django 6.0.4 on 2026-04-19 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('verification_code', models.CharField(editable=False, max_length=10, unique=True)),
                ('litres', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost_per_litre', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_value', models.DecimalField(decimal_places=2, editable=False, help_text='Auto-calculated: litres x cost_per_litre', max_digits=10)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('redeemed', 'Redeemed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='issued', max_length=15)),
                ('issue_datetime', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Optional. Set per coupon at issuance. If blank, no expiry applies.', null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Required when status is set to Cancelled.')),
                ('purpose', models.CharField(blank=True, help_text="Brief note on why fuel is being issued, e.g. 'VC airport run'.", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='drivers.driver')),
                ('fuel_station', models.ForeignKey(limit_choices_to={'is_active': True, 'type': 'fuel_station'}, on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='vendors.vendor')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_coupons', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'fuel_coupons',
                'ordering': ['-issue_datetime'],
            },
        ),
    ]
