# Generated by Django 4.2.30 on 2026-04-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelcoupon',
            name='coupon_id',
            field=models.CharField(editable=False, help_text='Auto-generated: NEU/FMS/CP/XXXXXX', max_length=24, unique=True),
        ),
        migrations.AddIndex(
            model_name='fuelcoupon',
            index=models.Index(fields=['coupon_id'], name='fuel_coupon_coupon__08ca11_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelcoupon',
            index=models.Index(fields=['status', 'issue_datetime'], name='fuel_coupon_status_4b9b24_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelcoupon',
            index=models.Index(fields=['vehicle', 'status'], name='fuel_coupon_vehicle_c11e95_idx'),
        ),
    ]
