# Generated by Django 4.2.30 on 2026-04-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_alter_fuelcoupon_coupon_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fuelcoupon',
            name='fuel_coupon_coupon__08ca11_idx',
        ),
        migrations.RemoveIndex(
            model_name='fuelcoupon',
            name='fuel_coupon_status_4b9b24_idx',
        ),
        migrations.RemoveIndex(
            model_name='fuelcoupon',
            name='fuel_coupon_vehicle_c11e95_idx',
        ),
        migrations.AlterField(
            model_name='fuelcoupon',
            name='coupon_id',
            field=models.CharField(editable=False, max_length=25, unique=True),
        ),
    ]
