# Generated by Django 4.2.30 on 2026-05-12 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupons', '0003_remove_fuelcoupon_fuel_coupon_coupon__08ca11_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelcoupon',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When the approval/rejection decision was made.', null=True),
        ),
        migrations.AddField(
            model_name='fuelcoupon',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved or rejected this coupon.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fuelcoupon',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Optional reason supplied by the approver when rejecting.'),
        ),
        migrations.AddField(
            model_name='fuelcoupon',
            name='requested_litres',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Original litres requested at issue, if the approver edited the amount.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fuelcoupon',
            name='self_approved',
            field=models.BooleanField(default=False, help_text='True if the issuer approved their own coupon. Surfaced in audit.'),
        ),
        migrations.AlterField(
            model_name='fuelcoupon',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('issued', 'Issued'), ('redeemed', 'Redeemed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=15),
        ),
    ]
