# Generated by Django 6.0.4 on 2026-04-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('staff_id', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('license_no', models.CharField(max_length=50, unique=True)),
                ('license_class', models.CharField(choices=[('A', 'Class A'), ('B', 'Class B'), ('C', 'Class C'), ('D', 'Class D'), ('E', 'Class E'), ('G', 'Class G')], max_length=5)),
                ('license_expiry', models.DateField(help_text='Used to trigger 30-day expiry alert.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'drivers',
                'ordering': ['full_name'],
            },
        ),
    ]
