# Generated by Django 4.2.30 on 2026-05-03 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLicenceRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_license_no', models.CharField(help_text='New licence number (can be same if renewal)', max_length=50)),
                ('new_expiry', models.DateField(help_text='New expiry date after renewal')),
                ('renewed_by', models.CharField(help_text='Name of staff who recorded this renewal', max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('renewed_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licence_renewals', to='drivers.driver')),
            ],
            options={
                'db_table': 'driver_licence_renewals',
                'ordering': ['-renewed_at'],
            },
        ),
    ]
