# Generated by Django 4.2.30 on 2026-05-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driverlicencerenewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='payment_type',
            field=models.CharField(choices=[('salaried', 'Salaried'), ('per_trip', 'Paid per Trip'), ('mixed', 'Mixed (Salary + Trip)')], default='salaried', help_text='How this driver is paid. Affects trip-logging defaults.', max_length=15),
        ),
    ]
