# Generated by Django 4.2.30 on 2026-05-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemodulepermission',
            name='can_approve',
            field=models.BooleanField(default=False, help_text='Approve/reject actions (currently used by Fuel Coupons; reserved for future approval workflows).'),
        ),
        migrations.AlterField(
            model_name='rolemodulepermission',
            name='module',
            field=models.CharField(choices=[('vehicles', 'Vehicle Management'), ('drivers', 'Driver Management'), ('coupons', 'Fuel Coupons'), ('fuel_logs', 'Fuel Logs'), ('maintenance', 'Maintenance'), ('vendors', 'Vendor Register'), ('reports', 'Reports'), ('dashboard', 'Dashboard'), ('users', 'User Management'), ('roles', 'Role Management'), ('audit', 'Audit Trail'), ('trips', 'Trips'), ('destinations', 'Destinations')], max_length=50),
        ),
    ]
