# Generated by Django 4.2.30 on 2026-05-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_station_deposits_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodulepermission',
            name='module',
            field=models.CharField(choices=[('vehicles', 'Vehicle Management'), ('generators', 'Generator Management'), ('drivers', 'Driver Management'), ('coupons', 'Fuel Coupons'), ('fuel_logs', 'Fuel Logs'), ('maintenance', 'Maintenance'), ('vendors', 'Vendor Register'), ('reports', 'Reports'), ('dashboard', 'Dashboard'), ('users', 'User Management'), ('roles', 'Role Management'), ('audit', 'Audit Trail'), ('trips', 'Trips'), ('destinations', 'Destinations'), ('settings', 'System Settings'), ('settings_email', 'SMTP / Email Settings')], max_length=50),
        ),
    ]
