# Generated by Django 4.2.30 on 2026-05-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportschedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='name',
            field=models.CharField(help_text='Friendly name for this schedule', max_length=120),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='recipients',
            field=models.TextField(help_text='Comma-separated email addresses'),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='report_type',
            field=models.CharField(choices=[('vehicle_spending', 'Per-Vehicle Spending'), ('monthly_expense', 'Monthly Expense'), ('maintenance', 'Maintenance History')], max_length=40),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='send_day',
            field=models.PositiveSmallIntegerField(default=1, help_text='Day of month to send (1-28). Use 1 for the 1st of each month.'),
        ),
    ]
