# Generated by Django 6.0.4 on 2026-04-19 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_litres', models.DecimalField(decimal_places=2, help_text='Actual litres dispensed. May be less than coupon amount.', max_digits=8)),
                ('actual_cost', models.DecimalField(decimal_places=2, help_text='Actual total cost paid.', max_digits=10)),
                ('fuel_date', models.DateField(help_text='Date the vehicle was actually fuelled.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.OneToOneField(help_text="The coupon being redeemed. Must be in 'Issued' status.", on_delete=django.db.models.deletion.PROTECT, related_name='fuel_log', to='coupons.fuelcoupon')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_logs', to='drivers.driver')),
                ('fuel_station', models.ForeignKey(blank=True, help_text="Defaults to coupon's fuel station. Editable if station differed.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuel_logs', to='vendors.vendor')),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_logs_entered', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_logs', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'fuel_logs',
                'ordering': ['-fuel_date'],
            },
        ),
    ]
