# Generated by Django 4.2.30 on 2026-05-15 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_coupon_generator_support'),
        ('fuel_logs', '0002_fuellog_generator_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuellog',
            name='coupon',
            field=models.OneToOneField(help_text='The coupon being redeemed.', on_delete=django.db.models.deletion.PROTECT, related_name='fuel_log', to='coupons.fuelcoupon'),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='fuel_date',
            field=models.DateField(help_text='Date the asset was actually fuelled.'),
        ),
    ]
