# Generated by Django 6.0.4 on 2026-04-19 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text="Snapshot of the user's name at time of action (preserved if user deleted).", max_length=150)),
                ('action', models.CharField(choices=[('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('coupon_issue', 'Coupon Issued'), ('coupon_redeem', 'Coupon Redeemed'), ('coupon_cancel', 'Coupon Cancelled')], max_length=20)),
                ('module', models.CharField(help_text='Which module/app the action occurred in.', max_length=50)),
                ('record_id', models.CharField(blank=True, help_text='PK or identifier of the affected record.', max_length=50)),
                ('detail', models.TextField(blank=True, help_text='Human-readable description of what changed.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
