# Generated by Django 4.2.30 on 2026-05-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditlog_approve_reject_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('coupon_issue', 'Coupon Issued'), ('coupon_redeem', 'Coupon Redeemed'), ('coupon_cancel', 'Coupon Cancelled')], max_length=20),
        ),
    ]
