# Generated by Django 4.2.30 on 2026-05-21 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station_deposits', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stationdeposit',
            new_name='station_dep_vendor__94be3a_idx',
            old_name='station_dep_vendor_d_idx',
        ),
    ]
