# Generated by Django 6.0.4 on 2026-04-19 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('service_type', models.CharField(choices=[('routine', 'Routine Service'), ('tyre', 'Tyre Change'), ('engine', 'Engine Repair'), ('electrical', 'Electrical'), ('bodywork', 'Bodywork'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(help_text='What was done — be specific.')),
                ('vendor_other', models.CharField(blank=True, help_text='Free-text for one-off / external vendors not in the register.', max_length=150)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('next_service_date', models.DateField(blank=True, help_text='Optional. Triggers dashboard alert within 14 days.', null=True)),
                ('approved_by', models.CharField(help_text='Name or designation of whoever authorised this expenditure.', max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='vehicles.vehicle')),
                ('vendor', models.ForeignKey(blank=True, help_text='Select from vendor register, or leave blank and use vendor_other.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to='vendors.vendor')),
            ],
            options={
                'db_table': 'maintenance_records',
                'ordering': ['-service_date'],
            },
        ),
    ]
