# Generated by Django 4.2.30 on 2026-05-12 15:30

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='description',
            field=models.TextField(blank=True, help_text='Optional overall summary. Individual work goes in line items.'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='service_type',
            field=models.CharField(blank=True, choices=[('routine', 'Routine Service'), ('tyre', 'Tyre Change'), ('engine', 'Engine Repair'), ('electrical', 'Electrical'), ('bodywork', 'Bodywork'), ('brakes', 'Brakes'), ('oil', 'Oil / Lubricants'), ('other', 'Other')], help_text='Primary service category. Auto-set from the first line item.', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Auto-calculated: sum of all MaintenanceItem costs.', max_digits=12),
        ),
        migrations.CreateModel(
            name='MaintenanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('routine', 'Routine Service'), ('tyre', 'Tyre Change'), ('engine', 'Engine Repair'), ('electrical', 'Electrical'), ('bodywork', 'Bodywork'), ('brakes', 'Brakes'), ('oil', 'Oil / Lubricants'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(help_text="What was done — be specific (e.g. 'Replaced front brake pads').", max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='maintenance.maintenancerecord')),
            ],
            options={
                'db_table': 'maintenance_items',
                'ordering': ['pk'],
            },
        ),
    ]
