# Generated by Django 6.0.4 on 2026-04-19 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bus', 'Bus'), ('van', 'Van'), ('truck', 'Truck'), ('motorcycle', 'Motorcycle'), ('other', 'Other')], max_length=20)),
                ('make', models.CharField(help_text='Manufacturer, e.g. Toyota', max_length=100)),
                ('model', models.CharField(help_text='Model name, e.g. Hilux', max_length=100)),
                ('year', models.PositiveSmallIntegerField(help_text='Year of manufacture')),
                ('colour', models.CharField(blank=True, max_length=50)),
                ('engine_no', models.CharField(blank=True, max_length=100)),
                ('chassis_no', models.CharField(blank=True, max_length=100)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('under_repair', 'Under Repair'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_vehicle', to='drivers.driver')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='accounts.department')),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['plate_number'],
            },
        ),
    ]
