# Generated by Django 4.2.30 on 2026-05-03 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetLicenceExpiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField(help_text='Date the fleet vehicle licences expire.')),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Fleet Licence Expiry',
                'db_table': 'fleet_licence_expiry',
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='needs_monthly_fuel',
            field=models.BooleanField(default=False, help_text='Flag vehicles that should receive fuel every month. Used to generate monthly fuel reminders.'),
        ),
        migrations.CreateModel(
            name='MonthlyFuelDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(help_text='Month number (1-12)')),
                ('year', models.PositiveSmallIntegerField(help_text='Year')),
                ('dismissed_by', models.CharField(max_length=150)),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_dismissals', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'monthly_fuel_dismissals',
                'unique_together': {('vehicle', 'month', 'year')},
            },
        ),
    ]
