# Generated by Django 4.2.30 on 2026-05-05 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driverlicencerenewal'),
        ('vehicles', '0002_fleetlicenceexpiry_vehicle_needs_monthly_fuel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverVehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(help_text='Snapshot of driver name at time of assignment', max_length=150)),
                ('assigned_by', models.CharField(max_length=150)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_assignments', to='drivers.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'driver_vehicle_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
