# Generated by Django 4.2.30 on 2026-05-12 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupons', '0004_fuelcoupon_approved_at_fuelcoupon_approved_by_and_more'),
        ('drivers', '0003_driver_payment_type'),
        ('vehicles', '0003_drivervehicleassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(blank=True, help_text="Optional short code, e.g. 'GMB', 'ABJ'.", max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_destinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'destinations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_other', models.CharField(blank=True, help_text='Free text for one-off origins not in the destination register.', max_length=150)),
                ('to_other', models.CharField(blank=True, help_text='Free text for one-off destinations not in the register.', max_length=150)),
                ('trip_date', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid to the driver for this trip.', max_digits=12)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='drivers.driver')),
                ('from_destination', models.ForeignKey(blank=True, help_text='From a registered destination. Leave blank to use from_other.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips_from', to='trips.destination')),
                ('fuel_coupons', models.ManyToManyField(blank=True, help_text='Optional: which fuel coupons were used for this trip.', related_name='trips', to='coupons.fuelcoupon')),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logged_trips', to=settings.AUTH_USER_MODEL)),
                ('to_destination', models.ForeignKey(blank=True, help_text='To a registered destination. Leave blank to use to_other.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips_to', to='trips.destination')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'trips',
                'ordering': ['-trip_date', '-created_at'],
            },
        ),
    ]
